# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build ffkb nice_nano_v2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["ffkb"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'
      # branches: '["UncleCJ/miryoku_zmk/nice_nano_v2-ffkb"]'
      alphas: '["QWERTY"]'
      nav: '["VI"]'
